### ISSUE TITLE
Create scale parent UI

### ISSUE THREAD

**Issue by pollockm** [LabVIEW-DCAF/TagEditorCore#198]
Provide a scale parent UI that provides a two-tab interface, one tab containing the set of input and output mappings that is static for all types of scales, and a second tab containing a subpanel to be overridden by specific scale types (e.g., polynomial scaling would have an array of coefficients)

**Comment by pollockm** [comment]
Current thoughts here:
![scaling ui](https://cloud.githubusercontent.com/assets/5288961/14506718/d085a546-0184-11e6-90af-dd83761b41ea.png)


https://dcaf.mybalsamiq.com/projects/scalingui/hybrid

**Comment by Beazurt** [comment]
This mockup is outstanding. Could we make more room on the UI by hiding the 'Configuration' pane somewhere? My feeling is that a user wouldn't interact with this often after the first definition of the scale. Maybe have a Mappings, and Configuration tab so that you can only see one at a time?

Also as a feature request, I think it'd be useful to have an export/import button for a list of scales. This would allow scales to be reused across various engines. The mappings would not be exported/imported, just the number of scales and their configuration.

**Comment by Beazurt** [comment]
BTW I don't think we need the Import/Export feature in the first version. I just brought it up to get your thoughts on how something like that could fit into the mockups.

**Comment by pollockm** [comment]
Yes, I currently have the mappings and configuration sections as a two-page tab control, since I ran out of space when implementing in LV.

Re: Import/Export: Not enough time to get this done for first release, but nothing preventing it for later.  Add it as an issue to the new Scaling repository and I'll add it to the backlog.

**Comment by pollockm** [comment]
Ok, scale parent looks solid at this point.  Closing.  https://github.com/LabVIEW-DCAF/Scaling
