### ISSUE TITLE
Where did our error definitions go?

### ISSUE THREAD

**Issue by pollockm** [LabVIEW-DCAF/TagEditorCore#348]
We used to have good error descriptions for our error codes.  Now DCAF errors are showing up as undefined:

![image](https://user-images.githubusercontent.com/5288961/30349557-f5894a6e-97d8-11e7-9c40-df69f0fc8212.png)

What happened to our error definition files?  

Marking this as prioritize, since this will be a support issue.

**Comment by pollockm** [comment]
In at least the case screenshotted above, the error dialog happens here: 
![image](https://user-images.githubusercontent.com/5288961/30399026-f8164d62-9897-11e7-9b24-5092e92016d6.png)

**Comment by pollockm** [comment]
I believe this is part of the template for Delete Line provided.

**Comment by theSloopJohnB** [comment]
Checking through the error files, I found a file that used to define the error @pollockm found in this issue - but has not changed in 3 years. It seems like this is more likely something we missed.
https://github.com/LabVIEW-DCAF/ModuleInterface/commits/master/source/TagBusModuleFramework-errors.txt

I ran into a similar issue with a different error code and thought they may be related:

I got this while running a main.vi.
![image](https://user-images.githubusercontent.com/26978265/30401990-cfb00f98-98a1-11e7-92c1-35cd116982dd.png)

My error seems to come from the class discovery singleton. Concerningly - I do have [CEF-errors.txt](https://github.com/NISystemsEngineering/CEF/blob/master/Trunk/CEF-errors.txt) installed into C:\Program Files (x86)\National Instruments\LabVIEW 2014\project\errors.

The undefined error only happens when running on the RT target - not the host. I talked to @dbendele about errors and he mentioned that error definitions usually need to be installed to the target to see them.

Is it generally the case that errors we custom define in DCAF are not defined on the rt target, and that we doom our users to generic messages on RT? Do we have a decent way of deploying these files?

**Comment by theSloopJohnB** [comment]
I verified that this is a part of the template for both static and dynamic modules.

**Comment by theSloopJohnB** [comment]
Closing this - moved to issues https://github.com/LabVIEW-DCAF/ModuleInterface/issues/32 and https://github.com/LabVIEW-DCAF/TagEditorCore/issues/352

**Comment by pollockm** [comment]
...and yet the scan engine issue happens on a desktop target.
