### ISSUE TITLE
Need a Mechanism for Mapping Channels In Modules Across Engines and Targets

### ISSUE THREAD

**Issue by Beazurt** [LabVIEW-DCAF/TagEditorCore#94]
This functionality is not prohibited by the framework, but nothing is done to make it easier.  I think we need some way to flag a channel's scope as being larger than the local engine, and allow connecting those channel's to other channel's with the same scope.  This should allow us to query channels for automapping (like the CVT module), and help add protections against multiple writers like the engine does.

**Comment by becega** [comment]
Right now we have the UDP module to communicate the 2 engines, this allows 2 modules to communicate. Adding the scope might add additional complexity without a large benefit.

**Comment by Beazurt** [comment]
This feature may be needed in the framework for future plugins like DDS or TSN. The UDP module that we have today also has a lot of limitations, some of which are caused by missing this functionality in the framework. It certainly isn't well-scoped yet, but I'd prefer to leave it open as a potential to-do even if it is a ways down the road.

**Comment by becega** [comment]
I don't think this needs to be something on the core, a TEC module implementation with dds should cover this case. @pollockm

**Comment by pollockm** [comment]
@becega  - We could bake DDS into the underlying framework without too much trouble (akin to the 'enable network publishing' option on shared variables today), at least for data broadcast/monitoring purposes.

Getting the single-writer concept to work correctly cross-target would be challenging.  It would more correctly be 'first writer only' rather than 'single writer'.  I'd have to go spelunking into the DDS QoS profiles to see what is available for exclusive writers.

**Comment by pollockm** [comment]
@becega - we can indeed set exclusive writers for DDS topics.  Even better, the writing ownership can change if the original writer goes away.
